### ISSUE TITLE
ioctl permission problem after reboot

### ISSUE THREAD

**Issue by ellypsis** [wknapik/openvpn-unroot#4]
I just install the script on ArchLinux with a fresh configuration of openvpn.
After launching the script with the right input (user, group), I am able to start the service with : 
`# systemctl start openvpn@client-unrooted.service`
But when I reboot the computer, I have this error : 
`openvpn[22446]: ROUTE_GATEWAY xxx.xxx.1.1/255.255.255.0 IFACE=wlp4s0 HWADDR=xx:xx:xx:xx:xx:xx
openvpn[22446]: ERROR: Cannot ioctl TUNSETIFF tun0-unrooted: Operation not permitted (errno=1)
openvpn[22446]: Exiting due to fatal error
kernel: tun: Universal TUN/TAP device driver, 1.6
ernel: tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
systemd[1]: openvpn@client-unrooted.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: openvpn@client-unrooted.service: Unit entered failed state.
ellypsis systemd[1]: openvpn@client-unrooted.service: Failed with result 'exit-code'.`
I don't really inderstand why there is a problem, because I have the client-unrooted in /etc/sudoers.d/
I just notice that in this file, the path given is `/etc/openvpn/update-resolv-conf`
Why not `/etc/openvpn/update-resolv-conf-unrooted` ?

**Comment by wknapik** [comment]
Hi @ellypsis. Sorry for the delay in replying, was busy, then away over the weekend.

As for the log, that's not enough information to figure out the problem, but first things first - let's see if I understand what happened here.

You ran `openvpn-unroot` as root, fed it a valid OpenVPN config and generated everything that was needed. Then you ran `systemctl start openvpn@client-unrooted.service` and everything worked as expected. Correct so far ?

Then you either ran `systemctl enable openvpn@client-unrooted.service` and rebooted, or rebooted and ran `systemctl start openvpn@client-unrooted.service` and the service failed to start, giving you the error message you pasted. Correct ? 

There's a bunch of things I'd need to know to properly debug this, but let's try something simple first and maybe we'll get lucky. The error is about insufficient permissions when trying to manipulate the tunnel device. This shouldn't be a problem if the device was successfully created on boot, according to the .netdev file generated by `openvpn-unroot`, which leads me to think that the device was not set up as expected. What does `ip addr show tun0-unrooted` say ? Could you check if you have a file called /etc/systemd/network/tun0-unrooted.netdev ? The contents of the file should look something like this:
```
[NetDev]
Kind=tun
Name=tun0-unrooted

[Tun]
Group=openvpn
User=openvpn
```

If the device and/or the .netdev file aren't there, then there's the cause. OpenVPN is trying to create the tunnel and fails, because it doesn't have the permissions to do that. Alternatively, the .netdev file could be there, but systemd-networkd could be having trouble setting up the device for some reason, which would be visible in your logs. Could you check for that using `journalctl` (e.g. `journalctl|grep tun0-unroot`) ?

I think there's a good chance this will lead us to the cause of the problem, but if not, we'll keep looking. Let me know what you find and we'll go from there.

PS. As for the sudoers file - this is correct. We're granting rights to call update-resolv-conf, not update-resolv-conf-unrooted, which is just a sudo wrapper.

**Comment by ellypsis** [comment]
Hi @wknapik . Thank you for your time.
Your summary is correct.
`ip addr show tun0-unrooted` gives nothing since the `Device "tun0-unrooted" does not exist.`
I checked the file /etc/systemd/network/tun0-unrooted.netdev and it's ok.
I already tried to run `journalctl|grep tun0-unroot` and I don't have any more log than what I posted earlier.
That's why I opened the issue. I don't know where to look for.

**Comment by wknapik** [comment]
Hmm, that's weird. I just added a .netdev file and rebooted to reproduce the problem, but it worked as it's supposed to:

```
$ cat /etc/systemd/network/foo.netdev
[NetDev]
Kind=tun
Name=foo

[Tun]
Group=network
User=openvpn
$ ip addr show foo
5: foo: <NO-CARRIER,POINTOPOINT,MULTICAST,NOARP,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 500
    link/none 
$
````
I even modified my unrooted vpn config to use the foo device and it worked.

According to the [documentation](https://www.freedesktop.org/software/systemd/man/systemd.netdev.html), systemd-networkd will create devices according to /etc/systemd/network/*.netdev configs when it starts. I assume you have systemd-networkd enabled, right ?

As a temporary fix, you can run this command, to create the missing device:
`openvpn --mktun --dev-type tun --dev tun0-unrooted --user openvpn --group network`
(You should change the user/group to whatever you chose. I used openvpn/network (and added the openvpn user to the group network))

I will look into it further, but for now, openvpn --mktun should get you going.

**Comment by ellypsis** [comment]
That's my fault, I didn't start the systemd-networkd service. I use netctl, so I didn't need it.
Now it works. Maybe you can had the info in the readme. It wasn't obvious for me.
Thanks!

**Comment by wknapik** [comment]
Ah. I'm still getting used to systemd and just made the, obviously incorrect, assumption that everyone using it on a network would have systemd-networkd enabled. 

I'll update the README with my next push.

Anyway, I'm glad things are working for you now. Thanks for taking the time to report this!
